import { unimplemented } from '../helpers';
export declare type FactionResource = {
    basic: Basic;
    territory: Territory;
    chain: Chain;
    currency: Currency;
    weapons: Weapons;
    armor: Armor;
    temporary: Temporary;
    medical: Medical;
    drugs: Drugs;
    boosters: Boosters;
    cesium: Cesium;
    mainnews: MainNews;
    mainnewsfull: MainNewsFull;
    attacknews: AttackNews;
    attacknewsfull: AttackNewsFull;
    fundsnews: FundsNews;
    fundsnewsfull: FundsNewsFull;
    armorynews: ArmoryNews;
    armorynewsfull: ArmoryNewsFull;
    crimenews: CrimeNews;
    crimenewsfull: CrimeNewsFull;
    membershipnews: MembershipNews;
    membershipnewsfull: MembershipNewsFull;
    crimes: Crimes;
    attacks: Attacks;
    attacksfull: AttacksFull;
    revives: Revives;
    revivesfull: RevivesFull;
    upgrades: Upgrades;
    stats: Stats;
    donations: Donations;
    chains: Chains;
    timestamp: Timestamp;
};
export declare type Basic = unimplemented;
export declare type Territory = unimplemented;
export declare type Chain = unimplemented;
export declare type Currency = unimplemented;
export declare type Weapons = unimplemented;
export declare type Armor = unimplemented;
export declare type Temporary = unimplemented;
export declare type Medical = unimplemented;
export declare type Drugs = unimplemented;
export declare type Boosters = unimplemented;
export declare type Cesium = unimplemented;
export declare type MainNews = unimplemented;
export declare type MainNewsFull = unimplemented;
export declare type AttackNews = unimplemented;
export declare type AttackNewsFull = unimplemented;
export declare type FundsNews = unimplemented;
export declare type FundsNewsFull = unimplemented;
export declare type ArmoryNews = unimplemented;
export declare type ArmoryNewsFull = unimplemented;
export declare type CrimeNews = unimplemented;
export declare type CrimeNewsFull = unimplemented;
export declare type MembershipNews = unimplemented;
export declare type MembershipNewsFull = unimplemented;
export declare type Crimes = unimplemented;
export declare type Attacks = unimplemented;
export declare type AttacksFull = unimplemented;
export declare type Revives = unimplemented;
export declare type RevivesFull = unimplemented;
export declare type Upgrades = unimplemented;
export declare type Stats = unimplemented;
export declare type Donations = unimplemented;
export declare type Chains = unimplemented;
export declare type Timestamp = {
    timestamp: number;
};
