import { unconfirmed, unimplemented } from '../helpers';
export declare type UserResource = {
    networth: Networth;
    bazaar: Bazaar;
    display: Display;
    inventory: Inventory;
    hof: Hof;
    travel: Travel;
    events: Events;
    messages: Messages;
    education: Education;
    medals: Medals;
    honors: Honors;
    notifications: Notifications;
    personalstats: PersonalStats;
    workstats: WorkStats;
    crimes: Crimes;
    icons: Icons;
    cooldowns: Cooldowns;
    money: Money;
    perks: Perks;
    battlestats: BattleStats;
    bars: Bars;
    profile: Profile;
    basic: Basic;
    attacks: Attacks;
    attacksfull: AttacksFull;
    revives: Revives;
    revivesfull: RevivesFull;
    stocks: Stocks;
    properties: Properties;
    jobpoints: JobPoints;
    merits: Merits;
    refills: Refills;
    discord: Discord;
    gym: Gym;
    timestamp: Timestamp;
};
export declare type Networth = {
    networth: {
        pending: unconfirmed<number>;
        wallet: unconfirmed<number>;
        bank: unconfirmed<number>;
        points: unconfirmed<number>;
        cayman: unconfirmed<number>;
        vault: unconfirmed<number>;
        piggybank: number | null;
        items: unconfirmed<number>;
        displaycase: number | null;
        bazaar: unconfirmed<number>;
        properties: unconfirmed<number>;
        stockmarket: unconfirmed<number>;
        auctionhouse: unconfirmed<number>;
        company: unconfirmed<number>;
    };
};
export declare type Bazaar = unimplemented;
export declare type Display = unimplemented;
export declare type Inventory = unimplemented;
export declare type Hof = unimplemented;
export declare type Travel = unimplemented;
export declare type Events = unimplemented;
export declare type Messages = unimplemented;
export declare type Education = unimplemented;
export declare type Medals = unimplemented;
export declare type Honors = unimplemented;
export declare type Notifications = unimplemented;
export declare type PersonalStats = unimplemented;
export declare type WorkStats = unimplemented;
export declare type Crimes = unimplemented;
export declare type Icons = unimplemented;
export declare type Cooldowns = unimplemented;
export declare type Money = unimplemented;
export declare type Perks = unimplemented;
export declare type BattleStats = unimplemented;
export declare type Bars = unimplemented;
export declare type Profile = unimplemented;
export declare type Basic = unimplemented;
export declare type Attacks = unimplemented;
export declare type AttacksFull = unimplemented;
export declare type Revives = unimplemented;
export declare type RevivesFull = unimplemented;
export declare type Stocks = unimplemented;
export declare type Properties = unimplemented;
export declare type JobPoints = unimplemented;
export declare type Merits = unimplemented;
export declare type Refills = unimplemented;
export declare type Discord = unimplemented;
export declare type Gym = unimplemented;
export declare type Timestamp = {
    timestamp: number;
};
